#!/bin/bash

if [ "${WAIT_CONTAINER}" == false ]; then
    exit 0
fi

log INFO "Waiting for the Odoo in ${WAIT_CONTAINER} to stop"

while ping -c1 "${WAIT_CONTAINER}" &> /dev/null; do
    log DEBUG "${WAIT_CONTAINER} responded to ping"
done

log DEBUG "${WAIT_CONTAINER} has stopped responding"

exit 0
