#!/usr/bin/env python
# Copyright 2017 LasLabs Inc.

import os

import odoobaselib
from odoobaselib.installer import Installer


if odoobaselib.AUTO_REQUIREMENTS:
    for repo in odoobaselib.addons_config().keys():
        req_file = os.path.join(
            odoobaselib.SRC_DIR, repo, 'requirements.txt',
        )
        if os.path.isfile(req_file):
            Installer('pip', req_file).install()
